cp ../../../../AlphaTDR2/papers/SUS-16-038/trunk/*.tex .
cp ../../../../AlphaTDR2/papers/SUS-16-038/trunk/*.bib .
cp ../../../../AlphaTDR2/papers/SUS-16-038/trunk/*.sh .
cp ../../../../AlphaTDR2/papers/SUS-16-038/trunk/*.txt .
cp ../../../../AlphaTDR2/papers/SUS-16-038/trunk/*.sh .
#cp ../../../../AlphaTDR2/papers/SUS-16-038/trunk/*.html .
cp ../../../../AlphaTDR2/papers/SUS-16-038/trunk/Figures/*.* ./Figures/
cp ../../../../AlphaTDR2/papers/SUS-16-038/trunk/Supplementary/*.* ./Supplementary/
cp ../../../../AlphaTDR2/papers/SUS-16-038/trunk/RootFilesAndTarFiles/*.* ./RootFilesAndTarFiles/
